### ISSUE TITLE
Not working with Node 12 - ReferenceError: primordials is not defined

### ISSUE THREAD

**Issue by Juraj-Masiar** [jrnewell/easy-zip2#10]
I'm having problem making this work using current NodeJS 12. Version LTS 10 works fine.
```
ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (C:\Users\Juraj\git\addons\test\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\Juraj\git\addons\test\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\Juraj\git\addons\test\node_modules\easy-zip2\node_modules\graceful-fs\fs.js:1)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
```

There some StackOverflow discussion for it here:
https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node

**Comment by jrnewell** [comment]
updating the dependencies to latest seemed to fix this issue, but now requires >=6.x node.  Published 3.0.0 package with the fix.
